# Generated by Django 4.2.7 on 2023-12-07 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=256, verbose_name='用户头像')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='邮箱')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('status', models.BooleanField(default=True, verbose_name='状态: 0禁用 1正常')),
                ('type', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='admin', max_length=16, verbose_name='用户角色')),
                ('website', models.CharField(blank=True, max_length=256, verbose_name='用户站点')),
                ('platform', models.CharField(blank=True, max_length=128, verbose_name='操作平台')),
                ('userIp', models.CharField(default='0.0.0.0', max_length=128, verbose_name='设备IP')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='设备位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('key', models.CharField(max_length=256, verbose_name='权限健')),
                ('parent_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='父级权限键（可选）')),
                ('auth', models.BooleanField(default=False, verbose_name='是否是权限按钮')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序字段')),
                ('status', models.BooleanField(default=True, verbose_name='状态：0正常 1禁用')),
                ('disabled', models.BooleanField(default=False, verbose_name='状态：0正常 1禁用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('role_name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='角色名称')),
                ('role_auth', models.CharField(max_length=64, verbose_name='角色标识')),
                ('perms', models.JSONField(blank=True, null=True, verbose_name='权限类别')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('status', models.BooleanField(default=True, verbose_name='状态: 0禁用 1正常')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='UserOptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=64, verbose_name='操作人')),
                ('operator_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='操作人ID')),
                ('module', models.CharField(max_length=256, verbose_name='操作模块')),
                ('platform', models.CharField(max_length=256, verbose_name='操作平台')),
                ('operator_ip', models.CharField(max_length=256, verbose_name='设备IP')),
                ('address', models.CharField(max_length=256, verbose_name='设备位置')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='操作内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_name', models.CharField(max_length=128, verbose_name='资源名称')),
                ('src_type', models.CharField(max_length=64, verbose_name='资源类型')),
                ('preview_path', models.CharField(max_length=256, verbose_name='资源预览路径')),
                ('download_path', models.CharField(max_length=256, verbose_name='资源下载路径')),
                ('delete_path', models.CharField(max_length=256, verbose_name='资源删除路径')),
                ('src_size', models.CharField(max_length=256, verbose_name='资源大小')),
                ('remark', models.CharField(max_length=256, verbose_name='备注')),
                ('status', models.BooleanField(default=True, verbose_name='状态: false禁用 true正常')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.account', verbose_name='用户')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.role', verbose_name='角色'),
        ),
    ]
