# Generated by Django 4.2.7 on 2023-12-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='文件名称')),
                ('type', models.CharField(max_length=64, verbose_name='文件类型')),
                ('url', models.CharField(max_length=256, verbose_name='下载地址')),
                ('remark', models.CharField(max_length=256, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
        ),
    ]
